version: "3.7"

volumes:
  testvolume:
    name: test-volume

networks:
  testnetwork:
    name: test-network

services:
  pg:
    image: postgres:12.0
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - testvolume:/var/lib/postgresql/data
    networks:
      - testnetwork
  test_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        API_PORT: ${API_PORT}
    restart: on-failure
    depends_on:
      - pg
    volumes:
      - ./:/src
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - testnetwork
    env_file:
      - .env
